spring.application.name=url-shortner
server.port=8081
server.servlet.context-path=/url

spring.datasource.url=jdbc:postgresql://ep-wild-feather-am4ida93-pooler.c-5.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_t4zCkpgD3FBO&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_t4zCkpgD3FBO
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#encoding
encoding-key=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
redis.lock.ttl.seconds=100
redis.default.ttl.seconds=60