spring.application.name=url-shortner
server.port=8081

spring.datasource.url=jdbc:postgresql://ep-wild-feather-am4ida93-pooler.c-5.us-east-1.aws.neon.tech/neondb?user={your_db}&password={your_password}&sslmode=require&channelBinding=require
spring.datasource.username={your_db}
spring.datasource.password={your_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


app.base-url=http://localhost:8081/api/v1/url/
app.default.url-expiry-time=7


#encoding
encoding-key=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
redis.lock.ttl.seconds=100
redis.default.ttl.seconds=60
redis.limit.max.tokens=10
redis.limit.ttl.seconds=60
